app:
  jwt:
    secret: secretsecretsecretsecretsecretsecret
    access-token-lifetime: 5
    refresh-token-lifetime: 90
  grpc:
    server:
      port: 50051
    report:
      host: localhost
      port: 50053
spring:
  liquibase:
    change-log: classpath:/db/changelog/v-1.0/changelog-v.1.0-cumulative.xml
  jpa:
    hibernate:
      ddl-auto: none
#  datasource:
#    url: jdbc:mysql://192.168.1.39:3306/crm
#    username: crm
#    password: crm