app:
  jwt:
    secret: secretsecretsecretsecretsecretsecret
    lifetime: 5
  grpc:
    server:
      port: 50051
    report:
      host: localhost
      port: 50053
spring:
  liquibase:
    change-log: classpath:/db/changelog/v-1.0/changelog-v.1.0-cumulative.xml
  jpa:
    hibernate:
      ddl-auto: none
#  datasource:
#    url: jdbc:postgresql://localhost:5432/newcrm
#    platform: postgres
#    username: crm
#    password: crm