spring:
  liquibase:
    change-log: classpath:/db/changelog/v-1.0/changelog-v.1.0-cumulative.xml
  jpa:
    hibernate:
      ddl-auto: none
#  datasource:
#    url: jdbc:postgresql://localhost:5432/newcrm
#    platform: postgres
#    username: crm
#    password: crm